### ISSUE TITLE
Could you make this to be able to use for ESP32?

### ISSUE THREAD

**Issue by WebSamuraiDaisuke** [vlasovskikh/intellij-micropython#100]
Actually this is not the issue. I wish you guys make this to be available to work for ESP32.

**Comment by CHN-STUDENT** [comment]
I try to setting by esp8266 but my device is esp32, it also work.

![image](https://user-images.githubusercontent.com/21209416/79201117-21fbba80-7e6a-11ea-8dfe-f6e8b77b5eae.png)

**Comment by vlasovskikh** [comment]
Yes, using ESP8266 as a workaround will give you most of the plugin functions for ESP32. Follow #44 for updates.
