### ISSUE TITLE
Auto Detect Broken in V1.1 for FTDI

### ISSUE THREAD

**Issue by jdjjm** [vlasovskikh/intellij-micropython#103]
Just updated to version 1.1 today and found the auto detect to be broken for a ftdi programmer.

Plugging in a ESP8266 directly works fine so it seems to be just an issue with the fdti. 

Would love to see this fixed as I use an fdti programmer for custom ESP boards and auto detect is much easier than specifying the port each time it changes.

**EDIT:**
My programmers vendor id is 0x0403 and port id is 0x6001 . 
This works with your findusb.py script.

Thanks

Micropython Plugin: V1.1
Windows 10
Pycharm 2020.1.1

**Comment by vlasovskikh** [comment]
@jdjjm Thanks for your report!

How do you feel about sending a one-line PR to the plugin? Alternatively I can just do it by myself.

If you're interested, the place where the USB IDs for ESP8266 are listed is [here](https://github.com/vlasovskikh/intellij-micropython/blob/6fee7d5df31d3c2933354eb7ab5dd21a49f26ad6/src/main/kotlin/com/jetbrains/micropython/devices/Esp8266DeviceProvider.kt#L27) in the code base. I have to ask you to electronically sign a contributor license agreement at http://www.jetbrains.com/agreements/cla/ Also it would be great if you built the plugin from sources as described in the [contribution docs](https://github.com/vlasovskikh/intellij-micropython#source-code) and checked it with your device.

**Comment by jdjjm** [comment]
I made the changes and built the plugin and it works. I have added a pull request like you asked.

**Comment by vlasovskikh** [comment]
Fixed by @jdjjm. Thanks!
