### ISSUE TITLE
Micropython language does not appear in Intellij

### ISSUE THREAD

**Issue by arpadtamasi** [vlasovskikh/intellij-micropython#110]
Hi, 

I've installed the plugin and trying to use it but MicroPython does not appear in the language list and is disabled under tools.
How can I activate it?

<img width="259" alt="image" src="https://user-images.githubusercontent.com/392101/85225614-e8e44700-b3d2-11ea-9dd6-3a956adf4cd6.png">

**Comment by vlasovskikh** [comment]
@arpadtamasi Is the MicroPython plugin enabled in your Settings | Plugins?

**Comment by arpadtamasi** [comment]
Sure


—

Arpad Tamasi
Principal Product manager at Rollbar

**Comment by vlasovskikh** [comment]
I’ve missed that you’re using IntelliJ, not PyCharm. The steps for setting up MicroPython support are different for them described in the docs:

> IntelliJ: Add the MicroPython facet to a Python module in your project structure and specify the path to your MicroPython device

So it’a in the Project Structure, not in Settings. See README.md for more details.

**Comment by arpadtamasi** [comment]
Thanks a lot, it works.
