### ISSUE TITLE
Unable to run any micropython in PyCharm for ESP8266

### ISSUE THREAD

**Issue by AstroDrabb** [vlasovskikh/intellij-micropython#120]
I was able to install the Micropython plugin into PyCharm 2020.2, however I can't get even the simplest of examples to work.  Example code:

```
import machine

def test(name) -> None:
    # Use a breakpoint in the code line below to debug your script.
    print(machine.freq())  # Press Ctrl+F8 to toggle the breakpoint.
    machine.freq(160000000)
    print(machine.freq())

if __name__ == '__main__':
    test()
```
```
Traceback (most recent call last):
  File "/home/jim/code/PycharmProjects/micropy-d1mini/main.py", line 6, in <module>
    import machine
ModuleNotFoundError: No module named 'machine'

Process finished with exit code 1
```
What step(s) am I missing to test and upload script to run?

**Comment by MyDataIsReady** [comment]
Had the same problem. Is your board being detected? Try to uninstall and install the plugin. Double-check dependencies are being installed without issues.

**Comment by AstroDrabb** [comment]
@MyDataIsReady I am using Linux, so no issues with drivers that I am aware of.  I will try to uninstall the plugin and reinstall.

**Comment by jdjjm** [comment]
@AstroDrabb by the look of your error message it looks like you are trying to run micropython code with regular python. You must run it on a micropython enabled microcontroller. Make sure you have enabled micropython support for the project by doing `Settings > Languages & Frameworks > MicroPython > Enable MicroPython Support`
If you right click on the file you have created you will now have the option to `Run 'Flash main.py'`. This will flash your script to your connected micropython device so it can run on there, not on your computer.

**Comment by vlasovskikh** [comment]
I agree with @jdjjm about the most likely source of this problem. Thanks @jdjjm for answering!

Closing this issue as answered.

**Comment by ram19890** [comment]
Please reopen this issue to investigate, the plugin failed to identify the actual board esp8266(It doesn't show "Flash main.py", it only shows Run 'main', using the default pyhon3.8). As you have mentioned already on the wiki that this board isn't supported, if in that case you can ignore my request! I am on MacOS 10.14.6 with pycharm 203.5981.165 installed, current mircopython plugin installed.

**Comment by hcet14** [comment]
I have the same problems. I'm using ESP8266 and ESP32. See also [https://forum.micropython.org/viewtopic.php?f=15&t=10771](url)
![github_issue](https://user-images.githubusercontent.com/38034498/124194702-5ab49d80-dac9-11eb-97a2-5511f203dc40.png)
![github_issue_board1](https://user-images.githubusercontent.com/38034498/124195187-33120500-daca-11eb-9403-4fff0db2cb2e.png)
![github_issue_board2](https://user-images.githubusercontent.com/38034498/124195201-3a391300-daca-11eb-958e-a22f71ee5a66.png)
Does the plugin tries to load the wrong board?
