### ISSUE TITLE
MicroPython REPL Not Working in Pycharm - takes me to virtual env.

### ISSUE THREAD

**Issue by states-lee-d** [vlasovskikh/intellij-micropython#121]
Hi,

Each time I try and run a serial connection with my board in Pycharm using the Micropython REPL tool, Pycharm takes me inside '(venv) C:\Users\xxxx\PycharmProjects\setup>'. I've followed instructions from multiple tutorials, yet not much seems to work. I'm on Windows 10.

Thanks

**Comment by bachi76** [comment]
Same here, Ubuntu.

**Comment by TishchenkoArtem** [comment]
Same problem, Windows 10

**Comment by functionpointer** [comment]
Same here, Windows 10. I am using the system interpreter and it just gives me a windows cmd shell in the project folder.

**Comment by Akshaya227** [comment]
@states-lee-d  I had the same issue. It was due to the version of Pycharm. The feature is not yet supported in 2020.2 it seems, so rollback to 2020.1 is suggested

**Comment by mathiaspez** [comment]
Same here, Pycharm 2020.2.3 under windows 10.

**Comment by fdesoye** [comment]
I currently work around with a manual REPL doing `screen /dev/tty.wchusbserial1420  115200` on a Mac with PyCharm 2020.2.3.
But would be great if I wouldn't have to apply this workaround.

**Comment by vlasovskikh** [comment]
The fix will be available soon in v1.1.2. Closing it as a duplicate of #117.

**Comment by vlasovskikh** [comment]
I've released 1.1.2 with the fix.

**Comment by mathiaspez** [comment]
Thank you!!!
Works like a (py)Charm! ;-)
Thank you again!
