### ISSUE TITLE
Failed to load plugin descriptor from file error

### ISSUE THREAD

**Issue by popeyesfx** [vlasovskikh/intellij-micropython#13]
Tried to install plugin on 2017.2.1 version of pycharm, but get the above error.
Tried re-downloading it but still will not load

**Comment by vlasovskikh** [comment]
How did you install the plugin? Is is the master branch from GitHub or the published version from the plugin repository?

**Comment by popeyesfx** [comment]
i tried to install from jetbrains but it said that it was not compatible with latest version of pycharm, so downloaded zip from github and tried to install from that but got the error message

**Comment by vlasovskikh** [comment]
Yes. The plugin 0.1 is incompatible with PyCharm 2017.2. Only with 2017.1. You can build the plugin from the master branch for 2017.2 as described in the readme. Don't hesitate to ask more questions if you encounter any issues.
