### ISSUE TITLE
ClassVar not recognised by linter, types as Any

### ISSUE THREAD

**Issue by hlovatt** [vlasovskikh/intellij-micropython#130]
This is strictly a PyCharm not MicroPython plugin issue, i.e https://youtrack.jetbrains.com/issue/PY-20811. However it is annoying in MicroPython since ClassVars are much more common, e.g. see attached image.

<img width="377" alt="Screen Shot 2021-01-03 at 7 10 05 pm" src="https://user-images.githubusercontent.com/8424169/103474642-02426300-4dfa-11eb-8b3f-f6abe2e0e3f7.png">

The linter types this as Any, which isn't that helpful.

Is it possible to up the priority of PyCharm issue PY-20811?

**Comment by vlasovskikh** [comment]
@hlovatt It's a major bug in PyCharm. There is no ETA yet, but it's on our radar. Please follow updates at the bug page.
