### ISSUE TITLE
Can't import uos in PyCharm

### ISSUE THREAD

**Issue by quaintdev** [vlasovskikh/intellij-micropython#137]
PyCharm keeps telling me that there is no module named uos but I can import it on esp8266 without any issue. Any suggestions?

**Comment by Wanyor** [comment]
You can use this tool to generate pyi stubs: [https://github.com/Josverl/micropython-stubber](url) , and place the stubs at C:\Users\Administrator\AppData\Roaming\JetBrains\PyCharmCE2020.3\plugins\intellij-micropython\typehints.

**Comment by Wanyor** [comment]
> PyCharm keeps telling me that there is no module named uos but I can import it on esp8266 without any issue. Any suggestions?

You can use this tool to generate pyi stubs: [micropython-stubber](https://github.com/Josverl/micropython-stubber) , and place the stubs at C:\Users\Administrator\AppData\Roaming\JetBrains\PyCharmCE2020.3\plugins\intellij-micropython\typehints.

**Comment by hlovatt** [comment]
it's on my list to create for https://github.com/hlovatt/PyBoardTypeshed and then hopefully it will be included in the Micropython plugin (many of the existing typesheds/stubs in Micropython come from this project). Give me a few weeks :).

**Comment by vlasovskikh** [comment]
Should be fixed by #176.
