### ISSUE TITLE
Micropython REPL error with pyserial 3.5 

### ISSUE THREAD

**Issue by d-marquina** [vlasovskikh/intellij-micropython#138]
Hi, I recently started tinkering with Micropython, ESP32 and Windows 10. Everything works perfectly except for the Micropython REPL: backspace and arrows are throwing strange characters.

I found out that this was an old issue regarding miniterm and pyserial 3.4, already resolved and closed. However, pyserial 3.5 was released last year and the problem came back.

The fastest solution was to downgrade pyserial to 3.4 but I wanted to report this behaviour.

**Comment by krzim** [comment]
I can confirm that I'm experiencing the same issue on Windows 10 with an ESP8266 and US keyboard. The downgrade to pyserial 3.4 resolves the issue.

**Comment by vlasovskikh** [comment]
It should be fixed by #175.
