### ISSUE TITLE
I can't send py files to ESP-01 by PyCharm  or uPyCraft. I need a guy who programmed ESP-01 with micropython language.  

### ISSUE THREAD

**Issue by electronic4706** [vlasovskikh/intellij-micropython#166]
Hello. dear productive friends. I need a guy who programmed ESP-01 with micropython language.  
 I have got 1 blue led version product. I am tries programming with micropython by PyCharm IDE.  I think that I flashed it with esp8266-512k-20190125-v1.10.bin by uPyCraft . however, connection is not successful, so couldn't send my files to it . upyCraft can't connect it . 
I am using MAKERFABS  CP2104 USB2UART Module. connection :
CP2104    ESP01
rx      ->       tx
tx      ->       rx
VIO   ->      3v3
DTR  ->      Rst
                   EN -> 3v3
                   DO0 -> GND
GND ->      GND
I flashed by upyCraft (Maybe I think so.) but i didn't send py files and i can't connection to ESP-01. 
I tried PyCharm. I saw com port but i didn't send files. 
Can any proactive guy help me, please ?

**Comment by Wanyor** [comment]
My SerialPort settings， you can try：

baudrate：115200

like this:
<img width="967" alt="截屏2021-06-06 下午8 37 11" src="https://user-images.githubusercontent.com/3807732/120924719-939a6600-c707-11eb-9b69-5297e56f7da9.png">

**Comment by electronic4706** [comment]
:) :) :)
