### ISSUE TITLE
Telnet support

### ISSUE THREAD

**Issue by legionnet** [vlasovskikh/intellij-micropython#17]
[telnet.zip](https://github.com/vlasovskikh/intellij-micropython/files/1292908/telnet.zip)

It will be convenient if project will have Telnet support for repl and for upload files

**Comment by vlasovskikh** [comment]
@legionnet Could you please elaborate on how you want telnet to be used for REPL and uploading?

**Comment by legionnet** [comment]
I use this telnet library [https://github.com/cpopp/MicroTelnetServer](url)
This library duplicate REPL by telnet

In previous post I send code for download and upload files by telnet.

**Comment by vlasovskikh** [comment]
Closing this one as it's not clear to me what's the use case for this feature and what exactly is requested here.
