### ISSUE TITLE
Incompatible with IDE build 211.* (current PyCharm version)

### ISSUE THREAD

**Issue by oxivanisher** [vlasovskikh/intellij-micropython#170]
The title tells it all. :)
The latest version is not compatible with the current PyCharm version (2021.2).

**Comment by PierreDeQuebec** [comment]
I have a professional version. By reflex, I updated to 2021.2. I never thought that the Micropython plugin would be disabled for lack of compatibility. But it 'trapped' me. So far, I have not been able to downgrade my professional license to version 2021.1.

As a way to get around the incompatibility:
- Return to Mu.
- Reinstall 2021.1

I chose to reinstall 2021.1 but in "Demo" version. This solution will work for 30 days. After? We'll see...

**Comment by vlasovskikh** [comment]
The fix will be available soon in 1.2.
