### ISSUE TITLE
Backspace and other keys not working as expected in REPL

### ISSUE THREAD

**Issue by Macgician** [vlasovskikh/intellij-micropython#175]
When using the Repl in pycharm, my backspace key sends a "<-[k" and if I hit backspace again the "K" is replaced by "<-[K"
Arrow keys are not working etc. pp. So corrections are not possible.

In the IDE text editor inside of PyCharm, this is not an issue.
Using PuTTY, this is not an issue.

I also get odd output for arrow keys and shift + arrow keys.
Is this a config setting in the plugin? Any solutions?

**Comment by jurekure** [comment]
Yes, i have same problem with the plugin.. it gets really hard to use it with this limitation

**Comment by zapalap** [comment]
Miniterm was finally patched with this fix: https://github.com/pyserial/pyserial/pull/351. It looks like this in turn broken the plugin again. 

I was able to fix the issue by removing the code from the miniterm fix that was introduced to the microrepl.py

Here's what I did

1) Removed the whole Windows10Console class from microrepl.py
https://github.com/vlasovskikh/intellij-micropython/blob/a068a81922151686142d01d93d4375c836ed92e6/scripts/microrepl.py#L82
2) Replaced the whole condition on line 168 with ```term = connect_miniterm(port)```
https://github.com/vlasovskikh/intellij-micropython/blob/a068a81922151686142d01d93d4375c836ed92e6/scripts/microrepl.py#L168

After that, backspace and arrows work again.

**Comment by itsmekingtiger** [comment]
> 
> 
> Miniterm was finally patched with this fix: [pyserial/pyserial#351](https://github.com/pyserial/pyserial/pull/351). It looks like this in turn broken the plugin again.
> 
> I was able to fix the issue by removing the code from the miniterm fix that was introduced to the microrepl.py
> 
> Here's what I did
> 
>     1. Removed the whole Windows10Console class from microrepl.py
>        https://github.com/vlasovskikh/intellij-micropython/blob/a068a81922151686142d01d93d4375c836ed92e6/scripts/microrepl.py#L82
> 
>     2. Replaced the whole condition on line 168 with `term = connect_miniterm(port)`
>        https://github.com/vlasovskikh/intellij-micropython/blob/a068a81922151686142d01d93d4375c836ed92e6/scripts/microrepl.py#L168
> 
> 
> After that, backspace and arrows work again.
> 
> @vlasovskikh I think this is quite a serious bug that turns off new users of the plugin. As it is right now the REPL is practically unusable. I can create a PR if you are ok with this.

It works to me, I edit file which located at `C:\Users\$USER\AppData\Roaming\JetBrains\$PYCHARM\plugins\intellij-micropython\scripts\microrepl.py`.

**Comment by vlasovskikh** [comment]
@zapalap Thanks for investigating it  I'll try your fix in the version I'm about to release.

I'd appreciate any help with testing the update on Windows.

**Comment by vlasovskikh** [comment]
I've reverted by original workaround for #43 now when we seem to have the proper fix in pyserial>=3.5.
