### ISSUE TITLE
Can't flash device

### ISSUE THREAD

**Issue by steeley** [vlasovskikh/intellij-micropython#197]
Can't flash a connected RP Pico...

terminal says"
```
Connecting to /dev/cu.usbmodem14101
Uploading files: 0% (0/1)
/Users/ian/PycharmProjects/microtest/main.py -> main.py
```

and nothing happens. Works fine in Thonny

**Comment by NotANormalNerd** [comment]
You have to make sure all REPLs are closed, since this uses the Python REPL to transfer files.
This includes everything outside of PyCharm as well.

**Comment by steeley** [comment]
did eventually get it working, but Pycharm+Micropython is not too great and have a load of other issues.
