### ISSUE TITLE
How to Install the Plugin with IntelliJ IDEA?

### ISSUE THREAD

**Issue by tobiashochguertel** [vlasovskikh/intellij-micropython#20]
I can't find the plugin in the Repository / Plugin Manager:

![image](https://user-images.githubusercontent.com/3332669/32282733-adee5a2a-bf22-11e7-8ff0-479c2a21fd23.png)

Is there a special Repository URL which I need to add first?

**Comment by Actpohomoc** [comment]
Same for me with PyCharm Pro and community editions

**Comment by vlasovskikh** [comment]
@tobiashochguertel @Actpohomoc The published version of the plugin is compatible only with IntelliJ 2017.1. Sorry for the inconvenience.

I will publish a version for 2017.2 (?) and 2017.3 later. Meanwhile you can get the source code and run:

```
./gradlew buildPlugin
```
Then you can go to "Preferences | Plugins" menu, click "Install plugin from disk" and choose build/distributions/intellij-micropython-*.zip.

Did it help?

**Comment by vlasovskikh** [comment]
@tobiashochguertel Thanks for the update!
