### ISSUE TITLE
Community edition - Could not resolve :pycharm:

### ISSUE THREAD

**Issue by Vjmorrison** [vlasovskikh/intellij-micropython#21]
Attempting to compile on Intellij Community edition for Pycharm Community Edition causes the following error.
```
Execution failed for task ':compileKotlin'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Could not resolve :pycharm:.
     Required by:
         project :
      > Could not resolve :pycharm:.
         > inconsistent module metadata found. Descriptor: com.jetbrains:ideaIC:2017.1 Errors: bad group: expected='' found='com.jetbrains'
           bad module name: expected='pycharm' found='ideaIC'
           bad version: expected='' found='2017.1'
      > Could not resolve :pycharm:.
         > inconsistent module metadata found. Descriptor: org.jetbrains.plugins:terminal:2017.1 Errors: bad group: expected='' found='org.jetbrains.plugins'
           bad module name: expected='pycharm' found='terminal'
           bad version: expected='' found='2017.1'
```

Is CE unsupported?  Is there an area I can do research for and submit a pull request on to support CE?

I'm operating under the assumption that most micropython users are not full purchasers of Python and rely solely on the CE version (like myself).

**Comment by vlasovskikh** [comment]
@Vjmorrison The plugin works with PyCharm Community, PyCharm Professional, IntelliJ Community, IntelliJ Ultimate.

Your log implies you're trying to build an old version of the plugin or you're using custom build options. The current version of PyCharm and IntelliJ is 2017.2, not 2017.1. Please make sure you're using the latest master branch.
