### ISSUE TITLE
seemingly broken under PyCharm 2017.3

### ISSUE THREAD

**Issue by boneskull** [vlasovskikh/intellij-micropython#22]
the IDE complains about a missing facet for my project, and the MicroPython options no longer appear in Settings, yet the plugin remains installed...

**Comment by boneskull** [comment]
screenshots:

![image](https://user-images.githubusercontent.com/924465/33504974-8cd9b83c-d69e-11e7-8d86-381fb9331ac3.png)

this warning remains after the plugin has been uninstalled

**Comment by vlasovskikh** [comment]
@boneskull Have you tried to build the plugin from the sources of the master branch at GitHub? The current version published at the JetBrains plugins repository is only compatible with PyCharm / IntelliJ 2017.1.

See also #24.
