### ISSUE TITLE
Support music module for Micro:bit

### ISSUE THREAD

**Issue by kylinpoet** [vlasovskikh/intellij-micropython#23]
Then,how to use it?

**Comment by vlasovskikh** [comment]
@kylinpoet Are you referring to the `music` module of BBC Micro:bit? We don't have a type hinting stub for this module yet. It means that the plugin won't be able to recognize methods from this module or provide code completion for it. [Here](https://github.com/vlasovskikh/intellij-micropython/tree/master/typehints/microbit) you can browse available type hints. A pull request with a stub for `music` would be welcome. The docs for the module are located [here](http://microbit-micropython.readthedocs.io/en/latest/tutorials/music.html).

**Comment by vlasovskikh** [comment]
Fixed in d3d8ef68264d876e5f86af56335c71382cb148fd.
