### ISSUE TITLE
Wrong pyserial version installed - installing 3.4 even though it causes requirements error.

### ISSUE THREAD

**Issue by Swington** [vlasovskikh/intellij-micropython#26]
Because of this, the Micropython REPL option was not available in Tools and all Micropython configurations had requirements errors. 
I had to manually change installed package version to 3.3 - then the problem disappeared and everything runs smoothly from there. 
Saw on system - Manjaro Linux. 
Pycharm Professional build 173.4127.16

**Comment by vlasovskikh** [comment]
@Swington Fixed in 1.0.3.
