### ISSUE TITLE
Missing machine.PWM, utime.ticks_diff() for MicroPython

### ISSUE THREAD

**Issue by plugowski** [vlasovskikh/intellij-micropython#47]
There is missing couple classes like machine.PWM or method utime.ticks_diff()

**Comment by vlasovskikh** [comment]
@plugowski Thanks for reporting it. Could you consider contributing the missing definitions you've discovered?  See the `typehints/` folder in the repository.

**Comment by hlovatt** [comment]
See https://github.com/hlovatt/PyBoardTypeshed for the required pyi file. You can manually install, see README at referenced GitHub address. Hopefully will become part of the plugin; have issued a pull request.

**Comment by vlasovskikh** [comment]
Should be fixed by #176.
