### ISSUE TITLE
No ADC class in machine.pyi

### ISSUE THREAD

**Issue by andreas-harmuth** [vlasovskikh/intellij-micropython#57]

**Comment by vlasovskikh** [comment]
@andreas-harmuth What MicroPython port do you use? Could you please point to the documentation page that describes the class you're referrring to? My quick search gave me `pyb.ADC`, not `machine.ADC`.

**Comment by andreas-harmuth** [comment]
Hi @vlasovskikh, I'm not completely sure what you mean by port. I'm using MicroPython for ESP8266 and ESP32, and found the documentation for machine.ADC  [here](http://docs.micropython.org/en/v1.9.3/esp8266/library/machine.ADC.html)

**Comment by vlasovskikh** [comment]
@andreas-harmuth Thanks for the link! For some reason `machine.ADC` is not mentioned at [the page](http://docs.micropython.org/en/v1.9.3/esp8266/library/machine.html) about the `machine` module for ESP8266.


By ports I meant the CPU type of your board. It's the terminology used by MicroPython, see their [project structure](https://github.com/micropython/micropython/tree/master/ports).

**Comment by JennaSys** [comment]
The latest version (1.10) [docs page](http://docs.micropython.org/en/latest/library/machine.html) now lists ADC.   PyCharm inspection is also missing machine.PWM however, which is still not listed in the docs for machine.  (I'm using 2018.3.5, ESP8266, Python 3.7.2)

**Comment by hlovatt** [comment]
The current version of Micropython uses `machine.pyi` from https://github.com/hlovatt/PyBoardTypeshed which includes both ADC and PWM, if you upgrade the plugin does the problem go away?

**Comment by hlovatt** [comment]
@fablableo Thanks for finding this mistake. I fixed up this error and a couple of others that I found as a consequence of improving the error checking to find the original mistake you reported!

You can install the fixed typesheds manually, see Manually install in IDE in README on https://github.com/hlovatt/PyBoardTypeshed.

**Comment by vlasovskikh** [comment]
Should be fixed by #176.
