### ISSUE TITLE
Terminal plugin required

### ISSUE THREAD

**Issue by CashOlsen** [vlasovskikh/intellij-micropython#61]
I've been unsuccessful in installing MicroPython plugin be cause I need a terminal plugin and have not located it.

A screen shot is provided in dropbox:
https://www.dropbox.com/s/akmh1u6r46bx208/Screenshot%202018-06-23%2018.28.55.png?dl=0

**Comment by vlasovskikh** [comment]
@CashOlsen I believe you're using PyCharm Edu which doesn't include the Terminal plugin. Currently the MicroPython plugin is compatible only with PyCharm Community, PyCharm Professional, IntelliJ Community, IntelliJ Ultimate.
