### ISSUE TITLE
There has been Solve the repl problem of winodws and support wireless programming, but how to merger?

### ISSUE THREAD

**Issue by junhuanchen** [vlasovskikh/intellij-micropython#64]
Hi

I used my mpfshell as the underlying layer.

And I also compiled a project demonstration

It's the same as my mpfshell.

Solve the repl problem of winodws

Support wireless programming path mode

I used esp32 and esp8266.

Other same as mpfshell

https://github.com/junhuanchen/mpfshell
https://github.com/junhuanchen/intellij-mpfshell

If you think it's good, would you consider a merger?

**Comment by vlasovskikh** [comment]
@junhuanchen What are the benefits of using mpfshell instead of adafruit-ampy and pyserial? Could issues on Windows 10 and wireless uploading be fixed by smaller changes without switching to another library for communicating with devices? adafruit-ampy and pyserial are widely used libraries. I have doubts about stability of mpfshell and the community around it.

**Comment by junhuanchen** [comment]
HI, good morning, here I am.

All right, let me explain. A couple of questions.


First, both adafruit - ampy mpfshell, the bottom is in [pyboard. Py] (https://github.com/micropython/micropython/blob/master/tools/pyboard.py), the dependence of pyserial.


Second, win10's repl control of messy code problem in pyserial console, it has nothing to do with adafruise-ampy or mpfshell.


Third, mpfshell differs from adafruit-ampy in that it supports more Linux commands, such as put/get/cat, including freely combined commands.


Finally, the mpfshell part I fixed is not only the Windows console problem of pyserial, but also the stable connection problem of pyboard.py (when connecting different devices), which is at least better than adafrutis-ampy, because the official connection board sub-process has not been fixed, you can have a try.


Because I understand the underlying communication mechanism of the board, I can fix all kinds of abnormal situations.

**Comment by vlasovskikh** [comment]
Sorry @junhuanchen, I don't consider switching to mpfshell-lite, as I mentioned in #88.
