### ISSUE TITLE
ESP266 file removal failure

### ISSUE THREAD

**Issue by cr0mbly** [vlasovskikh/intellij-micropython#68]
Thanks for all the work @vlasovskikh on this project have just started using it and I'm impressed how easy to use it is.

I've encountered a bug while using the ESP8266MOD removing files with the `Remove all files from the micropython device` call it returns a `Unknown Error removing file` on call. I've tracked down the issue to the `microcleanfs.py` script specifically here:

```
line 51: for name in files.ls():
 ...
```

at the moment this returns a verbose output of the file including the file in same string e.g. `['./main.py file size 443 bytes']` leading to the error above.

Changing this too.

`for name in files.ls((long_format=False)`

fixed it for me. Thoughts into putting into production?

**Comment by vlasovskikh** [comment]
The fix is in master. I'll release the plugin for PyCharm / IntelliJ 2018.3 shortly.
