### ISSUE TITLE
Setting device path (COM4) on Windows machine

### ISSUE THREAD

**Issue by Kortenbach** [vlasovskikh/intellij-micropython#71]
How do I set the device path to my NodeMCU board on a windows machine (COM4) with file-->Settings --> MicroPython?

**Comment by rftestman1** [comment]
Hi,

Apparently you would just put 'COM4' in the Device Path field as shown here:

![image](https://user-images.githubusercontent.com/34964563/48743038-6bbd8280-ec2f-11e8-9ba3-b22a1cd6401b.png)

But if you noticed my post from yesterday I am having some comms issue.  The REPL is working so the comms is partially working.  Let me know if you get it working.

Chris

**Comment by Kortenbach** [comment]
Thank you for your reply! Nice to get a confirmation that putting com4 should do the trick. I posted a second issue in which I'm asking for a hello blinky example cuz I cannot get it to work either... Anyone wants to share his to get a blinking LED working under Win10?

**Comment by Kortenbach** [comment]
This issue is resolved. Please look at issue "LED blink example #72"
