### ISSUE TITLE
LED blink example

### ISSUE THREAD

**Issue by Kortenbach** [vlasovskikh/intellij-micropython#72]
I found the learning curve to be quite steep if your not familiar with PyCharm. Could you provide an LED blink example, just to get up & running?

**Comment by rftestman1** [comment]
Have you seen this?:

https://blog.jetbrains.com/pycharm/2018/01/micropython-plugin-for-pycharm/

What board are you using?

**Comment by rftestman1** [comment]
Right click the project in the project window:

![image](https://user-images.githubusercontent.com/34964563/48800104-dbd31380-ecd6-11e8-973d-803cef7e5098.png)

Then select File and select the python file.

Pycharm is easy to use but takes some getting used to.  I would try some easier examples and come back to this one.  

I was hoping some of the experts would chime in on the comms problems but so far none have.

**Comment by Kortenbach** [comment]
Thanks! And how do I transfer the file? (Or is this part of the comms problem you mentioned?)

**Comment by rftestman1** [comment]
Yes, if working properly you just click the play button and the file is flashed to the chip.

![image](https://user-images.githubusercontent.com/34964563/48801280-f8247f80-ecd9-11e8-8795-94ea5b5b57d8.png)

**Comment by Kortenbach** [comment]
Thanks, I will look at this tomorrow, see if I get it to work! I'll tell if it worked.

**Comment by Kortenbach** [comment]
Ok, I'm starting to get the hang of it but it doesn't work...yet...
This is what I got:
C:\Users\user\PycharmProjects\TestPyCharm\venv\Scripts\python.exe C:\Users\user\.PyCharmCE2018.2\config\plugins\intellij-micropython/scripts/microupload.py -C C:/Users/user/PycharmProjects/TestPyCharm -v COM4 C:/Users/user/PycharmProjects/TestPyCharm/Blinky.py
Connecting to COM4
Traceback (most recent call last):
  File "C:\Users\user\.PyCharmCE2018.2\config\plugins\intellij-micropython/scripts/microupload.py", line 138, in <module>
    main(sys.argv[1:])
  File "C:\Users\user\.PyCharmCE2018.2\config\plugins\intellij-micropython/scripts/microupload.py", line 56, in main
    board = Pyboard(port)
  File "C:\Users\user\PycharmProjects\TestPyCharm\venv\lib\site-packages\ampy\pyboard.py", line 147, in __init__
    raise PyboardError('failed to access ' + device)
ampy.pyboard.PyboardError: failed to access COM4

**Comment by rftestman1** [comment]
So you are getting the same errors I was.  Just got it working.

You need to make sure the MicroPython REPL session is closed in order to release the serial port.

Output should look like this:

![image](https://user-images.githubusercontent.com/34964563/48865192-d04a2000-ed9c-11e8-883e-24ee9c7557a7.png)

**Comment by Kortenbach** [comment]
I'm not getting further than:
C:\Users\user\PycharmProjects\TestPyCharm\venv\Scripts\python.exe C:\Users\user\.PyCharmCE2018.2\config\plugins\intellij-micropython/scripts/microupload.py -C C:/Users/user/PycharmProjects/TestPyCharm -v COM4 C:/Users/user/PycharmProjects/TestPyCharm/Blinky.py
Connecting to COM4
Uploading files: 0% (0/1)
C:\Users\user\PycharmProjects\TestPyCharm\Blinky.py -> Blinky.py
And then it stops...
I also found that the COM port does't get released properly after use, so the next try it will raise the exception...

**Comment by Kortenbach** [comment]
Ok, now it works. Turns out my NodeMCU didn't like something I did and decided to stop working at some point. This made the upload proces fail and the COM port was left open because of that. I had to kill either Pycharm or the Python process to get the COM port to close again. Once I restarted my NodeMCU all was well. 
Thanks for the help!

**Comment by rftestman1** [comment]
Glad you got it working.   Was good to know someone else was having similar issues.  And I was not alone.

**Comment by Kortenbach** [comment]
Same here! Thanks again!

**Comment by ShivaniButle** [comment]
> So you are getting the same errors I was. Just got it working.
> 
> You need to make sure the MicroPython REPL session is closed in order to release the serial port.
> 
> Output should look like this:
> 
> ![image](https://user-images.githubusercontent.com/34964563/48865192-d04a2000-ed9c-11e8-883e-24ee9c7557a7.png)

My output is looking like this same but led is not blinking
