### ISSUE TITLE
the neopixel is missing  after update 

### ISSUE THREAD

**Issue by Monsoon117** [vlasovskikh/intellij-micropython#73]
The neopixel library is missing on micro:bit after update to 2018.3.

**Comment by Monsoon117** [comment]
The code can run. But the IDLE

**Comment by vlasovskikh** [comment]
It's not reproducible for me with a project in PyCharm 2018.3, intellij-micropython 1.0.10, and a Python 3.7 virtualenv.

What are the exact errors for the two lines marked in yellow on your screenshot?

**Comment by JennaSys** [comment]
I'm using PyCharm 2018.3.5, ESP8266, MicroPython plug-in v1.0.11, Python 3.7.2 on Windows 7 and inspection is reporting "No module named neopixel".

**Comment by hlovatt** [comment]
Isn't the problem that you don't have a pyi (type stub) for NeoPixel. See https://github.com/hlovatt/PyBoardTypeshed for the required pyi file. You can manually install, see README at referenced GitHub address. Hopefully will become part of the plugin; have issued a pull request.

**Comment by vlasovskikh** [comment]
Actually we already bundle `neopixel` with the MicroPython plugin. Please make sure you have selected Micro:bit as your device type in the MicroPython settings in PyCharm.
