### ISSUE TITLE
PyCharm PyBoard v1.1 Ubuntu 18.04 failed to access /dev/ttyACM0

### ISSUE THREAD

**Issue by mindfuucker** [vlasovskikh/intellij-micropython#75]
Hello,

I am trying to program my PyBoard v1.1 from my Ubuntu 18.04 system. 
1. Under Languages -> Micropython it failed to autodetect the device. 
2. When running: ampy.pyboard.PyboardError: failed to access /dev/ttyACM0
3. screen /dev/ttyACM0 -> [screen is terminating]

It was visible in my file explorer until I changed the mode in boot.py to "VCP"

**Comment by junhuanchen** [comment]
well，No permission to access your serial port.
you can try `usermod -a -G dialout Username && sudo reboot`, or search other `serial permission` question.

**Comment by vlasovskikh** [comment]
Closing this issue as obsolete. Feel free to open new ones.
