### ISSUE TITLE
Missing definition for ujson and umqtt

### ISSUE THREAD

**Issue by da4id** [vlasovskikh/intellij-micropython#78]

**Comment by hlovatt** [comment]
`ujson` on my list to create for https://github.com/hlovatt/PyBoardTypeshed and then hopefully it will be included in the Micropython plugin (many of the existing typesheds/stubs in Micropython come from this project). Give me a few weeks :).

`umqtt` isn't a standard Micropython library though?

**Comment by hlovatt** [comment]
See https://github.com/hlovatt/PyBoardTypeshed for the required pyi file. You can manually install, see README at referenced GitHub address. Hopefully will become part of the plugin; have issued a pull request.

**Comment by vlasovskikh** [comment]
Should be fixed by #176.
