### ISSUE TITLE
Open ESP8266 directory project

### ISSUE THREAD

**Issue by adispartadev** [vlasovskikh/intellij-micropython#80]
Hey, thank's for made this awesome plugin. This help me to learn Mycropython a lot. But I have a question.

![image](https://user-images.githubusercontent.com/16744864/50720026-4baf2900-10e0-11e9-8e15-c79be678b7d0.png)

Is this plugin enable to open directory from my ESP8266 project? When I using uPyCraft, this IDE automatic show directory in my ESP8266. How do I configure my pyCharm so it show my ESP8266 project folder, not my laptop project..

_This is the example when I using uPyCraft._ 
![image](https://user-images.githubusercontent.com/16744864/50720053-bc564580-10e0-11e9-9c33-3472b8771f35.png)

Thanks in advance

**Comment by vlasovskikh** [comment]
@adispartadev Sorry for my late reply. The intellij-micropython doesn't allow you to open a folder on a MicroPython device. Currently it's one-way sync of your project located on your computer that runs PyCharm to your MicroPython device. It's not even possible to browse the contents of your device (it might be a good enhancement, feel free to file an issue about it), let alone edit the files. The only two implemented functions of communicating with your MicroPython device are:

* Flash your local files or folder to your MicroPython device
* Run a REPL session on your MicroPython device
