### ISSUE TITLE
Failure writing files to target subdirectories from Windows OS

### ISSUE THREAD

**Issue by luisvgo** [vlasovskikh/intellij-micropython#82]
Flashing a Pycharm project with multiple subdirectories. Flashing fails writing subdirs content due to OSError: [Errno 2] ENOENT :
   ```
    ...
    raise PyboardError('exception', ret, ret_err)
    ampy.pyboard.PyboardError: ('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\nOSError: [Errno 2] ENOENT\r\n')
```
setup:
   * plugging v1.0.10 & v1.0.11
   * Windows 10 64
   * Pycharm 2018.3
   * ESP8266

microupload.py, receives path strings. 
When the string path has subdirs, a back-slash ('\\') separator is seen in Windows. The path is not created in the target if this is the case..
Replacing the separator to use posix paths solves the issue, 

Proposed solution in PR #86. 
Note: only tested with the mentioned setup

**Comment by vlasovskikh** [comment]
Merged #86 by @luisvgo.
