### ISSUE TITLE
Add type hints with documentation for 'pyb'

### ISSUE THREAD

**Issue by Walgensrl** [vlasovskikh/intellij-micropython#87]
Hi everybody,
I'm using Pycharm 2018.3.5 CE with Micropython plugin in Windows 7.
Everything works fine: I can access REPL for my NUCLEO board, I can flash file to my board.
The problem is I can't see Mycropython documentation for my code, just standard Python. If I place the cursor on my code snippet and press CTRL+Q it says no documentation found.

What am I doing wrong?
Many thanks.

Walter

![image](https://user-images.githubusercontent.com/48513119/54269658-072b8800-457e-11e9-9a73-6bf42612f92e.png)

**Comment by vlasovskikh** [comment]
@Walgensrl Sorry for my late reply. It's a bug in the intellij-micropython plugin. We still don't have type hinted stubs with documentation for Pyboard-specific MicroPython modules, including `pyb`.

**Comment by vlasovskikh** [comment]
This issue is a duplicate of #16.
