### ISSUE TITLE
XBEE not visible

### ISSUE THREAD

**Issue by paraglidingtech** [vlasovskikh/intellij-micropython#96]
Hello
I am on Mac OS 10,13.
There is no XBEE3  from Sparkfun that appears in the serial ports.

This is the same if I install a USB-Serial bridge.

Thank you

![Capture d’écran 2019-09-26 à 16 30 25](https://user-images.githubusercontent.com/55844060/65697348-12a65280-e07b-11e9-9fad-3bcbda98a5c7.png)

**Comment by vlasovskikh** [comment]
Hi @paraglidingtech! I'm sorry but [XBee MicroPython](https://plugins.jetbrains.com/plugin/12445-xbee-micropython) is a different third-party plugin not related the MicroPython plugin. Please contact them about your issue.
